# Netlify configuration file
# Place this in the root of your repo as `netlify.toml`

[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[build.environment]
  # This tells Netlify to skip the Next.js plugin entirely
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
