# Netlify configuration file
# Place this in the root of your repo as `netlify.toml`

[build]
  command = "npm run build"   # or "yarn build" if you use yarn
  publish = "dist"            # folder where your production build lives (change if different)

[build.environment]
  NODE_VERSION = "18"         # lock Node.js version
  NPM_VERSION = "9"           # optional: lock npm version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
