# Netlify configuration file
# Place this in the root of your repo as `netlify.toml`

[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[build.environment]
  NODE_VERSION = "18"         # lock Node.js version
  NPM_VERSION = "9"           # optional: lock npm version
